# Generated by Django 5.0.3 on 2024-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ingredients_recipe_is_ingredients_a_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default=True, unique=True),
            preserve_default=False,
        ),
    ]
